command :
  - python
  - wandb_sweep.py

project : DL_COPA

name : model Hyper parameter

method: bayes

metric:
  name: eval_acc
  goal: maximize

parameters:
  epoch :
    values : [5, 10, 15, 20, 25, 30]

  train_batch_size : 
    values : [4, 8, 16, 32, 64, 128, 256]

  test_batch_size : 
    values : [4, 8, 16, 32, 64, 128, 256]

  lr :
    values : [1e-1, 1e-2, 1e-3, 1e-4, 1e-5 , 1e-6]

  weight_decay :
    values : [1e-7, 2e-7, 3e-7, 4e-7]
    
